# Generated by Django 5.0.1 on 2024-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactlist',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='lastName',
            field=models.CharField(default='lastName', max_length=20),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='phone',
            field=models.CharField(default='9800000000', max_length=12),
        ),
    ]
