# Generated by Django 5.0.1 on 2024-03-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0003_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
