# Generated by Django 5.0.1 on 2024-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0004_customuser_is_admin_alter_customuser_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.TextField(blank=True, null=True),
        ),
    ]
