# Generated by Django 5.0.1 on 2024-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0008_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="/static/images/img_1.jpg", upload_to="media/"
                    ),
                ),
                ("intro", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
    ]
